# Generated by Django 6.0 on 2025-12-12 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RouteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_latitude', models.FloatField()),
                ('start_longitude', models.FloatField()),
                ('end_latitude', models.FloatField()),
                ('end_longitude', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('calculated', 'Calculated'), ('error', 'Error')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shortest_path_coords', models.JSONField(blank=True, help_text='List of [lat, lon] for shortest path', null=True)),
                ('optimized_path_coords', models.JSONField(blank=True, help_text='List of [lat, lon] for AI optimized path', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrafficSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_latitude', models.FloatField()),
                ('start_longitude', models.FloatField()),
                ('end_latitude', models.FloatField()),
                ('end_longitude', models.FloatField()),
                ('weight', models.FloatField(help_text='Imitated traffic weight or speed')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
